spring.application.name=notificacionesms
server.port=8096

spring.datasource.url=jdbc:mariadb://localhost:3307/canchas_notificaciones
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Apagamos Flyway
spring.flyway.enabled=false