spring.application.name=listanegrams
server.port=8094

spring.datasource.url=jdbc:mariadb://localhost:3307/canchas_listanegra
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true