server.port=8082
spring.application.name=ms-canchas

spring.datasource.url=jdbc:mariadb://localhost:3306/db_canchas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=false


servicio.estadisticas.url=http://localhost:8095/api/estadisticas