spring.application.name=estadisticasms
server.port=8095

spring.datasource.url=jdbc:mariadb://localhost:3306/db_estadisticas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Apagamos Flyway
spring.flyway.enabled=false