# Configuración del servidor
server.port=8081
spring.application.name=ms-pagos

# Conexión a la base de datos en tu XAMPP
spring.datasource.url=jdbc:mariadb://localhost:3306/db_pagos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de Hibernate y Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true