spring.application.name=inventarioms
server.port=8092

spring.datasource.url=jdbc:mariadb://localhost:3306/db_inventario
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Apagamos la creación automática de Hibernate y lo dejamos en modo revisión
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Encendemos Flyway para que sea el jefe absoluto de la base de datos
spring.flyway.enabled=true
spring.main.web-application-type=servlet