#1Microservicio
spring.application.name=ms-reservas

#2Puerto
server.port=8099

#3Base de Datos
spring.datasource.url=jdbc:mariadb://localhost:3306/db_reservas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=false

# 6. ENLACES ENTRE SERVICIOS
servicio.canchas.url=http://localhost:8082/api/canchas
servicio.usuarios.url=http://localhost:8089/api/usuarios
servicio.estadisticas.url=http://localhost:8095/api/estadisticas
servicio.estadisticas.url=http://localhost:8098/api/seguridad